### ISSUE TITLE
Specifiek

### ISSUE THREAD

**Issue by vasilisvg** [baskager/cssttr#20]
https://github.com/baskager/cssttr/blob/acaf6a42c0a05c1d44fbea6d5c213293037b9179/static/css/app.css#L285
Moet dit zo specifiek of kan dit ook efficienter?

**Comment by baskager** [comment]
Het is voor het submenu onder producten wat heel specifiek is en alleen in deze nav voorkomt. Ik weet niet of dit efficienter kan in dit geval.
